install:
 - yes | sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt5-default qtdeclarative5-dev
script:
 - qmake -project
 - qmake tests/ConsoleTest/ConsoleTest.pro
 - make
