language: objective-c
install:
- ./configure
script:
- qmake -project
#- qmake tests/ConsoleTest/ConsoleTest.pro
#- qmake tests/SDLTest/SDLTest.pro
#- qmake tests/FormTest/FormTest.pro
#- qmake tests/GraphicTest/GraphicTest.pro
#- qmake tests/GraphicStripTest/GraphicStripTest.pro
#- qmake tests/GraphicSyncTest/GraphicSyncTest.pro
#- qmake tests/VideoTest/VideoTest.pro
#- qmake tests/GraphicStripSyncTest/GraphicStripSyncTest.pro
- qmake app/Joker/Joker.pro
- make
notifications:
- email: false
