language: objective-c
install:
- ./scripts/bootstrap.sh
- export PATH=$PATH:/usr/local/opt/qt5/bin
script:
- mkdir tmp && cd tmp
# Build Joker
- mkdir Joker && cd Joker
- qmake ../../app/Joker/Joker.pro
- make
- cd ..
# Build AutoTest
- mkdir AutoTest && cd AutoTest
- qmake ../../tests/AutoTest/AutoTest.pro
- make
# Run AutoTest
- ./AutoTest
- cd .. 
notifications:
 irc: "irc.freenode.net#phonations"
 email: true

