language: objective-c
install:
- brew update
- brew install qt5 sdl2 sdl2_image sdl2_ttf
script:
- /usr/local/opt/qt5/bin/qmake -project
#- /usr/local/opt/qt5/bin/qmake tests/ConsoleTest/ConsoleTest.pro
- /usr/local/opt/qt5/bin/qmake tests/SDLTest/SDLTest.pro
#- /usr/local/opt/qt5/bin/qmake tests/FormTest/FormTest.pro
- make
notifications:
- email: false
