install:
# Install SDL2
- wget http://libsdl.org/release/SDL2-2.0.1.tar.gz
- tar -xvzf SDL2-2.0.1.tar.gz
- cd SDL2-2.0.1
- ./configure
- make
- sudo make install
- cd ..
# Install SDL2-image
- wget http://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz
- tar -xvzf SDL2_image-2.0.0.tar.gz
- cd SDL2_image-2.0.0
- ./configure
- make
- sudo make install
- cd ..
# Install SDL2-ttf
- wget http://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.12.tar.gz
- tar -xvzf SDL2_ttf-2.0.12.tar.gz
- cd SDL2_ttf-2.0.12
- ./configure
- make
- sudo make install
- cd ..
# Install Qt5
- yes | sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq qt5-default qtdeclarative5-dev
script:
- qmake -project
# - qmake tests/ConsoleTest/ConsoleTest.pro
- qmake tests/SDLTest/SDLTest.pro
- make
